language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/lingo_bingo_db_test

node_js:
  - "v14.17.6"

services:
  - postgresql

before_script:
  - psql -c 'create database  lingo_bingo_db_test;' -U postgres
  - psql -U postgres -d lingo_bingo_db_test -a -f table.sql

addons:
  apt:
    packages:
      - postgresql-server-dev-9.2