language: node_js
env:
  # - DATABASE_URL=postgresql://postgres@localhost:5432/e_smart_test

node_js:
  - "v14.17.6"

services:
  - postgresql

before_script:
  # - psql -c 'create database  e_smart_test;' -U postgres
  # - psql -U postgres -d e_smart_test -a -f migrations/001-create-waste-collector-table.sql
  # - psql -U postgres -d e_smart_test -a -f migrations/002-create-waste-donor-table.sql
  # - psql -U postgres -d e_smart_test -a -f migrations/003-create-waste-type-table.sql
  # - psql -U postgres -d e_smart_test -a -f migrations/010-create-waste-type-data-table.sql
  # - psql -U postgres -d e_smart_test -a -f migrations/004-create-waste-bin-table.sql

addons:
  apt:
    packages:
      - postgresql-server-dev-9.2